# Form implementation generated from reading ui file 'c:\Users\udtre\Projects\krita\plugins\impex\png\kis_wdg_options_png.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KisWdgOptionsPNG(object):
    def setupUi(self, KisWdgOptionsPNG):
        KisWdgOptionsPNG.setObjectName("KisWdgOptionsPNG")
        KisWdgOptionsPNG.resize(592, 381)
        self.gridLayout = QtWidgets.QGridLayout(KisWdgOptionsPNG)
        self.gridLayout.setObjectName("gridLayout")
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setHorizontalSpacing(0)
        self.gridlayout.setVerticalSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.label_4 = QtWidgets.QLabel(parent=KisWdgOptionsPNG)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 12, 0, 1, 1)
        self.compressionLevel = KisDoubleSliderSpinBox(parent=KisWdgOptionsPNG)
        self.compressionLevel.setObjectName("compressionLevel")
        self.gridlayout.addWidget(self.compressionLevel, 1, 1, 1, 2)
        self.bnTransparencyFillColor = KisColorButton(parent=KisWdgOptionsPNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bnTransparencyFillColor.sizePolicy().hasHeightForWidth())
        self.bnTransparencyFillColor.setSizePolicy(sizePolicy)
        self.bnTransparencyFillColor.setMinimumSize(QtCore.QSize(50, 0))
        self.bnTransparencyFillColor.setObjectName("bnTransparencyFillColor")
        self.gridlayout.addWidget(self.bnTransparencyFillColor, 12, 1, 1, 1)
        self.chkMetaData = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.chkMetaData.setObjectName("chkMetaData")
        self.gridlayout.addWidget(self.chkMetaData, 9, 1, 1, 1)
        self.textLabel3 = QtWidgets.QLabel(parent=KisWdgOptionsPNG)
        self.textLabel3.setObjectName("textLabel3")
        self.gridlayout.addWidget(self.textLabel3, 0, 1, 1, 1)
        self.chkForceSRGB = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.chkForceSRGB.setObjectName("chkForceSRGB")
        self.gridlayout.addWidget(self.chkForceSRGB, 7, 1, 1, 1)
        self.tryToSaveAsIndexed = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.tryToSaveAsIndexed.setChecked(True)
        self.tryToSaveAsIndexed.setObjectName("tryToSaveAsIndexed")
        self.gridlayout.addWidget(self.tryToSaveAsIndexed, 3, 1, 1, 1)
        self.interlacing = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.interlacing.setObjectName("interlacing")
        self.gridlayout.addWidget(self.interlacing, 4, 1, 1, 1)
        self.textLabel4_2 = QtWidgets.QLabel(parent=KisWdgOptionsPNG)
        self.textLabel4_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.textLabel4_2.setObjectName("textLabel4_2")
        self.gridlayout.addWidget(self.textLabel4_2, 0, 2, 1, 1)
        self.chkSaveAsHDR = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.chkSaveAsHDR.setObjectName("chkSaveAsHDR")
        self.gridlayout.addWidget(self.chkSaveAsHDR, 5, 1, 1, 1)
        self.textLabel1 = QtWidgets.QLabel(parent=KisWdgOptionsPNG)
        self.textLabel1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 1, 0, 2, 1)
        self.alpha = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.alpha.setChecked(True)
        self.alpha.setObjectName("alpha")
        self.gridlayout.addWidget(self.alpha, 8, 1, 1, 1)
        self.chkSRGB = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.chkSRGB.setObjectName("chkSRGB")
        self.gridlayout.addWidget(self.chkSRGB, 6, 1, 1, 1)
        self.chkAuthor = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.chkAuthor.setObjectName("chkAuthor")
        self.gridlayout.addWidget(self.chkAuthor, 10, 1, 1, 1)
        self.chkDownsample = QtWidgets.QCheckBox(parent=KisWdgOptionsPNG)
        self.chkDownsample.setObjectName("chkDownsample")
        self.gridlayout.addWidget(self.chkDownsample, 11, 1, 1, 1)
        self.gridLayout.addLayout(self.gridlayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(414, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)

        self.retranslateUi(KisWdgOptionsPNG)
        QtCore.QMetaObject.connectSlotsByName(KisWdgOptionsPNG)

    def retranslateUi(self, KisWdgOptionsPNG):
        _translate = QtCore.QCoreApplication.translate
        KisWdgOptionsPNG.setWindowTitle(_translate("KisWdgOptionsPNG", "PNG Options"))
        self.label_4.setText(_translate("KisWdgOptionsPNG", "Transparent color: "))
        self.compressionLevel.setToolTip(_translate("KisWdgOptionsPNG", "Note: the compression level does not change the quality of the result"))
        self.compressionLevel.setWhatsThis(_translate("KisWdgOptionsPNG", "<p>Adjust the compression time. Better compression takes longer.\n"
"<br>Note: the compression level does not change the quality of the result.</p>"))
        self.bnTransparencyFillColor.setToolTip(_translate("KisWdgOptionsPNG", "<html><head/><body><p>Background color to replace transparent pixels with.</p></body></html>"))
        self.chkMetaData.setToolTip(_translate("KisWdgOptionsPNG", "<html><head/><body><p>Store information like keywords, title and subject and license, if possible.</p></body></html>"))
        self.chkMetaData.setText(_translate("KisWdgOptionsPNG", "Store Metadata"))
        self.textLabel3.setWhatsThis(_translate("KisWdgOptionsPNG", "<p>Adjust the compression time. Better compression takes longer.\n"
"<br>Note: the compression level does not change the quality of the result.</p>"))
        self.textLabel3.setText(_translate("KisWdgOptionsPNG", "Large file size", "The file will save fast but will not be compressed a lot"))
        self.chkForceSRGB.setText(_translate("KisWdgOptionsPNG", "Force convert to sRGB"))
        self.tryToSaveAsIndexed.setToolTip(_translate("KisWdgOptionsPNG", "Indexed PNG images are smaller. If you enabled this option, your image will be analyzed to see whether it is possible to save as an indexed PNG."))
        self.tryToSaveAsIndexed.setText(_translate("KisWdgOptionsPNG", "Save as indexed PNG, if possible"))
        self.interlacing.setToolTip(_translate("KisWdgOptionsPNG", "Use interlacing when publishing on the Internet."))
        self.interlacing.setWhatsThis(_translate("KisWdgOptionsPNG", "<p>Interlacing is useful if you intend to publish your image on the Internet.<br>\n"
"Enabling interlacing will cause the image to be displayed by the browser even while downloading.</p>"))
        self.interlacing.setText(_translate("KisWdgOptionsPNG", "Interlacing"))
        self.textLabel4_2.setWhatsThis(_translate("KisWdgOptionsPNG", "<p>Adjust the compression time. Better compression takes longer.\n"
"<br>Note: the compression level does not change the quality of the result.</p>"))
        self.textLabel4_2.setText(_translate("KisWdgOptionsPNG", "Small file size", "The compression will take a long time; saving the file will be slow."))
        self.chkSaveAsHDR.setText(_translate("KisWdgOptionsPNG", "Save as HDR image (Rec. 2020 PQ)"))
        self.textLabel1.setToolTip(_translate("KisWdgOptionsPNG", "Note: the compression level does not change the quality of the result"))
        self.textLabel1.setWhatsThis(_translate("KisWdgOptionsPNG", "<p>Adjust the compression time. Better compression takes longer.\n"
"<br>Note: the compression level does not change the quality of the result.</p>"))
        self.textLabel1.setText(_translate("KisWdgOptionsPNG", "Compression (Lossless): "))
        self.alpha.setToolTip(_translate("KisWdgOptionsPNG", "Disable to get smaller files if your image has no transparency"))
        self.alpha.setWhatsThis(_translate("KisWdgOptionsPNG", "<p>The Portable Network Graphics (PNG) file format allows transparency in your image to be stored by saving an alpha channel.\n"
"You can uncheck the box if you are not using transparency and you want to make the resulting file smaller .<br>Always saving the alpha channel is recommended.</p>"))
        self.alpha.setText(_translate("KisWdgOptionsPNG", "Store alpha channel (transparency)"))
        self.chkSRGB.setToolTip(_translate("KisWdgOptionsPNG", "<html><head/><body><p><span style=\" font-weight:600;\">PNG</span> files have <span style=\" font-style:italic;\">two</span> options to save <span style=\" font-weight:600;\">sRGB</span> information: as a tag or as an explicit profile. For use with in websites, <span style=\" font-style:italic;\">disable</span> this option. For interchange with other applications, <span style=\" font-style:italic;\">enable</span> this option.</p></body></html>"))
        self.chkSRGB.setText(_translate("KisWdgOptionsPNG", "Embed sRGB profile"))
        self.chkAuthor.setToolTip(_translate("KisWdgOptionsPNG", "<html><head/><body><p>Save author nickname and the first contact information of the author profile into the png, if possible.</p></body></html>"))
        self.chkAuthor.setText(_translate("KisWdgOptionsPNG", "Sign with author data"))
        self.chkDownsample.setText(_translate("KisWdgOptionsPNG", "Force convert to 8 bits/channel"))
from kis_color_button import KisColorButton
from kis_slider_spin_box import KisDoubleSliderSpinBox
