# SPDX-FileCopyrightText: 2026 Solstice contributors
# SPDX-License-Identifier: BSD-3-Clause
#
# Script mode helper of SolsticeEmbedRcc.cmake: writes INPUT as the byte
# array SYMBOL into OUTPUT.

file(READ "${INPUT}" hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
# 32 bytes per line (CMake regular expressions have no {n} quantifier)
set(line_pattern "")
foreach(i RANGE 1 32)
    string(APPEND line_pattern "0x[0-9a-f][0-9a-f],")
endforeach()
string(REGEX REPLACE "(${line_pattern})" "\\1\n" bytes "${bytes}")
file(WRITE "${OUTPUT}"
    "// Generated by SolsticeEmbedRccToCpp.cmake from ${INPUT}\n"
    "extern const unsigned char ${SYMBOL}[];\n"
    "alignas(16) const unsigned char ${SYMBOL}[] = {\n${bytes}\n};\n")
